### ISSUE TITLE
Requested claims are missing when "Subject Claim URI:" is not selected. 

### ISSUE THREAD

**Issue by JKAUSHALYA** [wso2-extensions/identity-inbound-auth-oauth#906]
**Description:**
$subject
Fix: https://github.com/wso2-extensions/identity-inbound-auth-oauth/commit/89db22a3fa4741a662ffaf16eaeecfecb3cf52cd#diff-2279172db0d5fdaeff54eee493c2a4afR133

**Suggested Labels:**
N/A

**Suggested Assignees:**
N/A

**Affected Product Version:**
5.2.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by darshanasbg** [comment]
Created an issue in https://github.com/wso2/product-is/issues/3332 and closing this..
