### ISSUE TITLE
DefaultTokenBuilder does not add "at_hash" field to the ID token claims

### ISSUE THREAD

**Issue by dilin993** [wso2-extensions/identity-inbound-auth-oauth#908]
**Description:**
When an access token is requested, the given response with id token does not contain the "at_hash" property.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
IS 5.5.6-rc3

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Setup a service provider with Oauth/OpenID Connect configuration. 

Send a request with password grant type.

**Related Issues:**

**Comment by dilin993** [comment]
Fixed with https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/909

**Comment by alexfdezsauco** [comment]
How to install the update of this fix into wso2is 5.6?
